name: 'Mend Slack Notifier'

on:
  discussion:
    types: [labeled]

permissions:
  discussions: read

jobs:
  slack:
    if: contains(github.event.label.name, 'mend-app')
    runs-on: ubuntu-latest
    steps:
      - name: Post to Slack
        id: slack
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          channel-id: 'C05NLTMGCJC'
          # For posting a simple plain text message
          slack-message: '<${{ github.event.discussion.html_url }}|${{ github.event.discussion.title }}>'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
